### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by santiago-imelio** [santiago-imelio/metnum#1]
### Systems of equations
- [x] Jacobi
- [x] Gauss-Seidel
- [x] Successive over-relaxation (SOR)

### Eigenvalues and eigenvectors
...

### Root finding
- [x] Newton-Raphson
- [ ] Bisection method
- [ ] Secant method
- [ ] Regula Falsi method
- [ ] Fixed point method

### Ordinary differential equations
- [ ] Euler method
- [ ] Trapezoidal rule ([might overlap with Scholar](https://github.com/elixir-nx/scholar/blob/main/lib/scholar/integrate/integrate.ex#L439))
- [ ] Runge-Kutta

### Extrema finding
- [ ] Golden Ratio search
